services:
  backend:
    build: 
      context: ./dnc_backend
      dockerfile: Dockerfile_backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_URL}:${DB_PORT}/${DB_NAME}
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./dnc_frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
