[package]
name = "dnc_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
tokio = { version="1.48.0", features = ["full"] }
serde = {version="1.0.228", features = ["derive"]}
serde_json = "1.0.145"