services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: no
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-ap-southeast-1.grafana.net
      - GRAFANA_INSTANCE_ID=${GRAFANA_INSTANCE_ID}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics (Collector's own health)
      - "13133:13133" # Health check extension
